export const REFLECTION_PAGE_CHAPTER_COMPLETE = 'REFLECTION_PAGE_CHAPTER_COMPLETE';
export const REFLECTION_PAGE_LEARNING = 'REFLECTION_PAGE_LEARNING';
export const REFLECTION_PAGE_CHAPTER_REFLECTION_RESPONSES = 'REFLECTION_PAGE_CHAPTER_REFLECTION_RESPONSES';
export const REFLECTION_PAGE_CHAPTER_OUTCOME = 'REFLECTION_PAGE_CHAPTER_OUTCOME';

export const REFLECTION_PAGE_STORY_COMPLETE = 'REFLECTION_PAGE_STORY_COMPLETE';

export const REFLECTION_PAGE_FORM = 'REFLECTION_PAGE_FORM';