export const REFLECTION_PAGE_CHAPTER_COMPLETE = 'REFLECTION_PAGE_CHAPTER_COMPLETE';
export const REFLECTION_PAGE_CHAPTER_REFLECTION_RESPONSES = 'REFLECTION_PAGE_CHAPTER_REFLECTION_RESPONSES';
export const REFLECTION_PAGE_FORM = 'REFLECTION_PAGE_FORM';